import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { copy, locales, translatedServices, type Locale } from "../../localized";
import { company } from "../../data";
import { ReferenceStrip } from "../../components";
import { pageMetadata } from "../../seo-metadata";

type LocalService={slug:string;tr:string;title:string;summary:string;intro:string;items:readonly string[]};
const base="https://besenerji.net";
const valid=(value:string):value is Locale=>locales.includes(value as Locale);
const getServices=(locale:Locale):readonly LocalService[]=>locale==="en"?translatedServices.en:translatedServices.ar;
const sectionNames=(locale:Locale)=>locale==="en"?{services:"services",about:"about",projects:"projects",contact:"contact"}:{services:"الخدمات",about:"عن-الشركة",projects:"المشاريع",contact:"اتصل-بنا"};

export function generateStaticParams(){return locales.flatMap(locale=>{const names=sectionNames(locale);return [{locale,segments:undefined},{locale,segments:[names.services]},{locale,segments:[names.about]},{locale,segments:[names.projects]},{locale,segments:[names.contact]},...getServices(locale).map(service=>({locale,segments:[names.services,service.slug]}))]})}

function alternates(locale:Locale,segments?:string[]){let tr="/",en="/en",ar="/ar";if(segments?.length===1){const names=sectionNames(locale);const type=Object.entries(names).find(([,value])=>value===segments[0])?.[0] as keyof ReturnType<typeof sectionNames>|undefined;if(type){tr={services:"/hizmetler",about:"/kurumsal",projects:"/cozumler",contact:"/iletisim"}[type];en=`/en/${sectionNames("en")[type]}`;ar=`/ar/${sectionNames("ar")[type]}`}}if(segments?.length===2){const service=getServices(locale).find(item=>item.slug===segments[1]);if(service){tr=`/hizmetler/${service.tr}`;en=`/en/services/${translatedServices.en.find(item=>item.tr===service.tr)?.slug}`;ar=`/ar/الخدمات/${translatedServices.ar.find(item=>item.tr===service.tr)?.slug}`}}return{tr,en,ar}}

export async function generateMetadata({params}:{params:Promise<{locale:string;segments?:string[]}>}):Promise<Metadata>{const {locale,segments}=await params;if(!valid(locale))return{};const t=copy[locale],service=segments?.length===2?getServices(locale).find(item=>item.slug===segments[1]):undefined,alt=alternates(locale,segments),names=sectionNames(locale),section=segments?.[0];const title=service?.title??(section===names.services?t.services:section===names.about?t.about:section===names.projects?t.projects:section===names.contact?t.contact:locale==="en"?"Transformer Maintenance, Testing and Repair":"صيانة واختبار وإصلاح المحولات");const description=service?.summary??(section===names.contact?`${t.contact}: ${company.phoneDisplay} · ${company.email}`:t.heroText);return pageMetadata({title:`${title} | BES Energy`,description,path:`/${locale}${segments?.length?`/${segments.join("/")}`:""}`,locale:locale==="en"?"en_US":"ar_AR",languages:{tr:`${base}${alt.tr}`,en:`${base}${alt.en}`,ar:`${base}${alt.ar}`,"x-default":`${base}${alt.tr}`}})}

function Header({locale}:{locale:Locale}){const t=copy[locale],names=sectionNames(locale);return <header className="site-header"><div className="shell header-inner"><Link href={`/${locale}`} className="brand"><Image src="/images/bes-enerji-logo-concept-v3.png" alt="BES Energy" width={180} height={75}/></Link><nav><Link href={`/${locale}`}>{t.home}</Link><Link href={`/${locale}/${names.services}`}>{t.services}</Link><Link href={`/${locale}/${names.about}`}>{t.about}</Link><Link href={`/${locale}/${names.projects}`}>{t.projects}</Link><Link href={`/${locale}/${names.contact}`}>{t.contact}</Link></nav><span className="languages"><Link href="/">TR</Link><Link href="/en">EN</Link><Link href="/ar">العربية</Link></span><details className="mobile-menu"><summary>{locale==="ar"?"القائمة":"Menu"}</summary><div><Link href={`/${locale}`}>{t.home}</Link><Link href={`/${locale}/${names.services}`}>{t.services}</Link><Link href={`/${locale}/${names.about}`}>{t.about}</Link><Link href={`/${locale}/${names.projects}`}>{t.projects}</Link><Link href={`/${locale}/${names.contact}`}>{t.contact}</Link><Link href="/">TR</Link><Link href="/en">EN</Link><Link href="/ar">العربية</Link></div></details></div></header>}
function Footer({locale}:{locale:Locale}){const t=copy[locale];return <><ReferenceStrip/><section className="cta-band"><div className="shell cta-band-inner"><div><span className="kicker light">{t.support}</span><h2>{t.supportTitle}</h2><p>{t.supportText}</p></div><a className="btn white" href={`tel:${company.phone}`}>{t.call}</a></div></section><footer><div className="shell copyright">© 2026 BES Energy · {company.phoneDisplay} · {company.email}</div></footer></>}
function Cards({locale}:{locale:Locale}){const t=copy[locale],names=sectionNames(locale);return <div className="service-grid">{getServices(locale).map((service,index)=><Link className="service-card" href={`/${locale}/${names.services}/${service.slug}`} key={service.slug}><span className="number">0{index+1}</span><div className="service-body"><h3>{service.title}</h3><p>{service.summary}</p><span className="arrow">{t.learn} →</span></div></Link>)}</div>}

export default async function Page({params}:{params:Promise<{locale:string;segments?:string[]}>}){const {locale,segments}=await params;if(!valid(locale))notFound();const t=copy[locale],names=sectionNames(locale),service=segments?.length===2?getServices(locale).find(item=>item.slug===segments[1]):undefined,section=segments?.[0],ar=locale==="ar";if(segments?.length===2&&!service)notFound();let content;
if(service)content=<><section className="service-hero"><div className="shell service-hero-grid"><div><span className="kicker light">{t.services}</span><h1>{service.title}</h1><p>{service.intro}</p><div className="actions"><a className="btn primary" href={`tel:${company.phone}`}>{t.call}</a><a className="btn ghost" href="https://wa.me/905532124761">WhatsApp</a></div></div><div className="service-hero-image"><Image src={`/images/resim-${getServices(locale).findIndex(item=>item.slug===service.slug)+1}.jpeg`} alt={service.title} fill sizes="50vw"/></div></div></section><section className="section"><div className="shell content-grid"><div><span className="kicker">{t.scope}</span><h2>{t.scopeTitle}</h2><p className="lead">{service.summary}</p></div><ul className="check-list">{service.items.map(item=><li key={item}>{item}</li>)}</ul></div></section><section className="soft-section"><div className="shell"><span className="kicker">{t.process}</span><div className="process-grid">{t.steps.slice(0,3).map((step,index)=><article key={step}><span>0{index+1}</span><h3>{step}</h3></article>)}</div></div></section></>;
else if(section===names.services)content=<><section className="page-hero"><div className="shell"><span className="kicker light">{t.expertise}</span><h1>{t.expertiseTitle}</h1><p>{t.expertiseText}</p></div></section><section className="section"><div className="shell"><Cards locale={locale}/></div></section></>;
else if(section){const contact=section===names.contact,projects=section===names.projects;content=<><section className="page-hero"><div className="shell"><span className="kicker light">BES Energy</span><h1>{contact?t.contact:projects?t.projects:t.about}</h1><p>{contact?`${company.phoneDisplay} · ${company.email} · ${company.address}`:projects?t.expertiseText:t.whyText}</p></div></section>{projects&&<section className="section"><div className="shell gallery">{[2,4,6,8,10].map(number=><figure key={number}><Image src={`/images/resim-${number}.jpeg`} alt="BES Energy field project" fill sizes="33vw"/></figure>)}</div></section>}</>;
}
else content=<><section className="home-hero"><Image src="/images/bes-hero-concept.png" alt="Transformer and high-voltage installation illustration" fill priority sizes="100vw"/><div className="hero-shade"/><div className="shell hero-copy"><span className="kicker light">{t.heroKicker}</span><h1>{t.hero}</h1><p>{t.heroText}</p><div className="actions"><Link className="btn primary" href={`/${locale}/${names.contact}`}>{t.cta}</Link><a className="btn ghost" href={`tel:${company.phone}`}>{t.call}</a></div></div></section><section className="section"><div className="shell"><div className="section-head"><div><span className="kicker">{t.expertise}</span><h2>{t.expertiseTitle}</h2></div><p>{t.expertiseText}</p></div><Cards locale={locale}/></div></section><section className="dark-section"><div className="shell split"><div><span className="kicker light">{t.why}</span><h2>{t.whyTitle}</h2><p>{t.whyText}</p></div><div className="metric-grid">{t.steps.map((step,index)=><div key={step}><strong>0{index+1}</strong><span>{step}</span></div>)}</div></div></section></>;
return <div lang={locale} dir={t.dir} className={ar?"rtl":""}><Header locale={locale}/><main>{content}</main><Footer locale={locale}/></div>}
