import type { Article } from "./blog-data";
import { articlesTr } from "./blog-data";

const common = (index: number) => ({ id: articlesTr[index].id, service: articlesTr[index].service, equipment: articlesTr[index].equipment, sources: articlesTr[index].sources });

export const articlesEn: Article[] = [
  { ...common(0), slug: "how-often-transformer-maintenance", title: "How often should a transformer be maintained?", description: "A condition-based guide to transformer maintenance intervals, inspections and test planning.", intro: "There is no single maintenance interval suitable for every transformer. Manufacturer guidance, operating duty, environment, criticality and previous findings should determine the plan.", sections: [
    { heading: "Use risk, not an automatic calendar", body: "An annual review may be a starting point, but it is neither a universal requirement nor proof that every test must be repeated annually. Heat, dust, humidity, heavy loading and repeated protection operations may justify shorter inspection intervals.", bullets: ["Manufacturer instructions and site procedures", "Load and temperature trends", "Past failures and measurement changes", "Environmental severity and business criticality"] },
    { heading: "Different checks need different outages", body: "Visual inspection, thermal scanning, oil sampling and de-energized electrical tests are not interchangeable. Insulation and winding tests generally require a controlled outage, while some observations can be made during normal operation by qualified personnel." },
    { heading: "Update the plan after each visit", body: "Record leaks, loose connections, hot spots and measurement deviations with equipment identification and test conditions. The next visit and any corrective action should follow the trend of these findings, not simply a calendar anniversary." },
  ], faq: [{ q: "Does every transformer need a complete annual test?", a: "No. The test program depends on equipment type, manufacturer instructions, past results and operating risk." }, { q: "What information helps build a maintenance plan?", a: "Nameplate details, operating loads, environment and past maintenance and test reports are useful starting points." }] },
  { ...common(1), slug: "transformer-fault-warning-signs", title: "Transformer fault warning signs", description: "How to recognize abnormal sound, temperature, oil leaks and protection trips without jumping to an unsafe diagnosis.", intro: "Unusual sound, heat, oil leakage or a protection trip can indicate a developing problem. One symptom alone does not reveal the fault location or cause; site safety and event records come first.", sections: [
    { heading: "Signals worth investigating", body: "Changes from normal sound or vibration, high temperature, reduced oil level, smoke, unusual odor and repeated breaker operation warrant prompt assessment. A relay trip may originate in the transformer, cable, breaker or protection chain.", bullets: ["Abnormal sound, vibration or smell", "Oil or temperature changes", "Gas and other protection events", "Repeated trips or voltage issues"] },
    { heading: "First, protect people", body: "Keep unauthorized people away. Only qualified personnel should isolate, lock out and verify absence of voltage under site procedures. Preserve the time of the event and relay records; do not approach unsafe equipment to confirm a symptom." },
    { heading: "Find the root cause", body: "Inspection, event logs and selected insulation, ratio, winding and oil tests narrow the possibilities. Compare results with nameplate values and prior reports. After repair, verify relevant functions before controlled re-energization." },
  ], faq: [{ q: "Does a relay trip prove the transformer has failed?", a: "No. The transformer, cable, breaker and protection record must be assessed together." }, { q: "What if there is smoke or a burning smell?", a: "Secure the area, follow the facility emergency procedure and contact qualified responders." }] },
  { ...common(2), slug: "transformer-oil-dga-breakdown-testing", title: "Transformer oil analysis: DGA and breakdown testing", description: "What dissolved gas, moisture, acidity and dielectric breakdown tests reveal about transformer oil.", intro: "Transformer oil provides insulation and cooling. Oil testing adds useful condition data, but no single gas or breakdown value is a complete fault diagnosis.", sections: [
    { heading: "Each test answers a different question", body: "Breakdown voltage measures the stress a sample withstands. Moisture and acidity show other aspects of oil condition. Dissolved gas analysis (DGA) monitors gas levels and trends associated with thermal and electrical events.", bullets: ["BDV: dielectric strength", "Moisture and acidity: contamination and ageing", "DGA: gas levels and rate of change", "Sampling conditions: context for interpretation"] },
    { heading: "Sampling matters", body: "Contamination, air exposure, incorrect containers and poor labeling can distort results. Record the transformer identity, sampling date and operating condition. The method and repeated test sequence belong in the report." },
    { heading: "Translate data into action", body: "Interpret gas patterns and rates alongside load history, previous oil results, electrical tests and inspection findings. A repeat sample, oil treatment or further investigation may be appropriate. Testing frequency follows risk and manufacturer guidance, not one fixed interval for all units." },
  ], faq: [{ q: "Does low breakdown voltage always mean an internal fault?", a: "No. Sampling quality, moisture and contamination can also affect the result." }, { q: "Can DGA replace all other oil tests?", a: "No. DGA, BDV, moisture and other measurements answer different questions." }] },
  { ...common(3), slug: "mv-switchgear-maintenance-testing-guide", title: "MV switchgear maintenance and testing guide", description: "The mechanical, electrical and protection checks that belong in a medium-voltage switchgear program.", intro: "MV switchgear performs critical switching and protection functions. Maintenance includes more than cleaning: breakers, busbars, cable terminations, interlocks, auxiliary supplies and protection must be considered together.", sections: [
    { heading: "Physical and mechanical checks", body: "Look for arc traces, moisture, contamination, loose connections and wear. Verify breakers, disconnectors, door interlocks and earthing switches according to the equipment manual. Intrusive work requires secure isolation.", bullets: ["Busbars and cable terminations", "Breaker and disconnector mechanisms", "Mechanical interlocks and earthing", "Auxiliary supply and control wiring"] },
    { heading: "Electrical tests", body: "Depending on design, tests can include insulation resistance, contact resistance, breaker timing and relay functions. Secondary injection assesses protection settings and trip circuits. Primary injection is not automatically required or suitable for every installation." },
    { heading: "Intervals and records", body: "Manufacturer instructions, operation count, environmental severity and past findings influence frequency. Abnormal operation or a fault trip may call for an unscheduled inspection. Record equipment identity, test conditions, findings and actions." },
  ], faq: [{ q: "Must MV switchgear be de-energized for maintenance?", a: "Internal inspection and contact work require safe isolation and voltage-absence verification." }, { q: "Does every panel get the same tests?", a: "No. The panel, breaker and protection design determine the test plan." }] },
  { ...common(4), slug: "dry-type-transformer-maintenance", title: "Dry-type transformer maintenance", description: "Dust, ventilation, thermal condition and insulation checks for dry-type transformers.", intro: "The absence of oil does not mean a dry-type transformer needs no maintenance. Dust, humidity, cooling and connection temperature still require attention, while oil sampling and DGA do not apply.", sections: [
    { heading: "Environment and cleanliness", body: "Check airflow, filters, dust build-up and moisture in the transformer room. Choose cleaning methods specified by the manufacturer; unsuitable compressed air or solvents can damage insulation surfaces.", bullets: ["Air passages and fans", "Coils and insulation surfaces", "Dust and humidity", "Temperature sensors and alarms"] },
    { heading: "Measurements and thermal review", body: "Where appropriate, examine connections, insulation resistance and thermal images. More advanced diagnostic methods depend on the transformer design and symptoms. Interpret readings with test temperature, duration and previous trends." },
    { heading: "Record and follow up", body: "Document contamination, looseness, hot spots or insulation concerns. Keep corrective work and repeated measurements with the same equipment record. Adjust the review interval to environment and operational criticality." },
  ], faq: [{ q: "Is oil analysis used on a dry-type transformer?", a: "No. There is no oil to sample." }, { q: "Are dry-type transformers maintenance-free?", a: "No. Environment, cooling, connections and insulation still need checking." }] },
  { ...common(5), slug: "transformer-tests-explained", title: "Transformer tests: what does each measurement show?", description: "The roles of TTR, winding resistance, insulation, tan delta and oil tests in transformer assessment.", intro: "Tests turn hidden equipment conditions into measured evidence. Select them for the symptom and transformer type; applying every test to every unit without a technical reason is not good practice.", sections: [
    { heading: "The main electrical test families", body: "TTR assesses winding ratio and tap behavior; winding resistance examines connections and contacts; insulation resistance reviews the insulation system. Tan delta and capacitance support deeper dielectric assessment. Oil-filled units have additional oil tests.", bullets: ["TTR: ratio and vector group", "Winding resistance: phase and tap comparison", "Insulation resistance: insulation trends", "Tan delta: dielectric losses", "Oil tests: electrical and chemical oil condition"] },
    { heading: "How results are interpreted", body: "Compare with nameplate values, manufacturer tolerances, temperature, test connections and historical records. Check the method first if a value is suspicious and use complementary tests where justified. No single threshold applies to every model." },
    { heading: "Why reporting matters", body: "The instrument, temperature, phase and tap position matter alongside the reading. A complete report provides a baseline for later comparison and makes maintenance decisions auditable." },
  ], faq: [{ q: "Is a TTR test enough on its own?", a: "No. It investigates particular faults and must be interpreted with other findings." }, { q: "Are all these tests performed on energized equipment?", a: "No. Many require the equipment to be safely de-energized." }] },
  { ...common(6), slug: "what-to-do-transformer-emergency", title: "What to do during a transformer emergency", description: "Safety-first steps, information to preserve and the path to a controlled return to service.", intro: "After an unexpected outage, the goal is not simply the fastest restart but a safe one. Protect people and the site, then give qualified responders accurate event information.", sections: [
    { heading: "Safety in the first minutes", body: "If there is smoke, fire, leaking oil or unusual noise, prevent unauthorized access and follow the facility emergency procedure. Only authorized staff should perform switching or intervention. Never touch or approach equipment to confirm a suspected fault.", bullets: ["Secure the area", "Follow the site's emergency procedure", "Record event time and visible symptoms", "Preserve relay and breaker logs"] },
    { heading: "What to tell the technical team", body: "Provide the location, transformer nameplate, tripped protection device, last maintenance date and available test history. A 24/7 phone line is a contact channel, not a promise of instant arrival; response and travel time are agreed after reviewing the case." },
    { heading: "Safe return to service", body: "The cause may lie in the transformer, switchgear, cable or protection chain. Inspection and selected tests guide the repair. Do not re-energize until relevant functions and safety conditions have been verified." },
  ], faq: [{ q: "Does a 24/7 line mean immediate on-site arrival?", a: "No. The phone line is available around the clock; on-site response is arranged case by case." }, { q: "Should power be restored immediately after a trip?", a: "Not before the cause and necessary checks are addressed." }] },
  { ...common(7), slug: "used-transformer-buying-checklist", title: "Used transformer buying checklist", description: "Check nameplate, history, physical condition and electrical test results before purchasing a used transformer.", intro: "A used transformer's price is only part of the decision. Missing records or tests may create significant safety and cost exposure after installation.", sections: [
    { heading: "Nameplate and history", body: "Confirm rated power, voltages, vector group, impedance, year and cooling type against the receiving facility. Request maintenance, fault, transport and storage records. An unreadable nameplate may call for additional verification.", bullets: ["Power, voltage and vector group", "Leaks, corrosion and physical damage", "Maintenance and transport history", "Technical fit with the new installation"] },
    { heading: "A suitable test package", body: "Oil-filled and dry-type units require different physical checks. TTR, insulation and winding-resistance tests are selected by equipment type and condition. Compare findings with nameplate and historical values where available." },
    { heading: "The purchase decision", body: "Consider warranty terms, transport, installation, spare parts and commissioning cost as well as test results. Suspicious findings may justify conditional acceptance, further testing or rejecting the unit." },
  ], faq: [{ q: "Is a used transformer safe to buy without test records?", a: "The technical risk is greater. Appropriate tests and history should be reviewed before purchase." }, { q: "Is the same checklist valid for oil and dry types?", a: "Some electrical and nameplate checks overlap, but oil and cooling checks differ." }] },
];
