export type Article = {
  id: string;
  slug: string;
  title: string;
  description: string;
  intro: string;
  sections: { heading: string; body: string; bullets?: string[] }[];
  faq: { q: string; a: string }[];
  service: string;
  equipment?: string;
  sources: { label: string; url: string }[];
};

const sources = {
  maintenance: { label: "Hitachi Energy — Routine Maintenance", url: "https://www.hitachienergy.com/products-and-solutions/transformers/transformer-service/parts-and-maintain/routine-maintenance" },
  testing: { label: "Megger — Transformer testing and monitoring", url: "https://www.megger.com/en/products/trax-multifunction-transformer-and-substation-test-system" },
  oil: { label: "Hitachi Energy — Dissolved gas and moisture monitoring", url: "https://www.hitachienergy.com/products-and-solutions/transformers/the-txpert-ecosystem/txpert-ready-sensors/txpert-ready-multi-gas-dga-analyzer-coresense-m10" },
  bdv: { label: "Megger — Insulating oil breakdown testing", url: "https://www.megger.com/en-gb/products/ots-pb-and-ots-af-series-insulating-oil-test-sets" },
  switchgear: { label: "Schneider Electric — MV switchgear inspection and maintenance", url: "https://www.productinfo.schneider-electric.com/sureset_tech_lit/nnz9886800-sureset-mv-indoor-switchgear-user-guide/English/NNZ9886800%20%28bookmap%29.xml/%24/InspectionAndMaintenance-A092B399" },
  dry: { label: "OMICRON — Diagnostic testing of cast-resin transformers", url: "https://www.omicronenergy.com/en/news/details/diagnostic-testing-of-cast-resin-transformers/" },
  ttr: { label: "Megger — Transformer turns ratio testing", url: "https://www.megger.com/en/support/technical-library/academic-papers/transformer-turns-ratio-test-some-unknown-facts" },
  winding: { label: "Megger — Winding resistance testing", url: "https://www.megger.com/en-gb/transformer-resistance-testing" },
};

export const articlesTr: Article[] = [
  { id: "bakim-sikligi", slug: "trafo-bakimi-ne-siklikla-yapilmali", title: "Trafo bakımı ne sıklıkla yapılmalı?", description: "Yağlı ve kuru tip trafolarda bakım periyodu; yük, ortam, üretici talimatı ve önceki test sonuçlarına göre nasıl belirlenir?", intro: "Trafo bakımında tek bir takvimi bütün tesislere uygulamak doğru değildir. Bakım aralığı, üretici talimatı ve mevzuat gereklilikleriyle birlikte yük profili, çevre koşulları, ekipman yaşı ve geçmiş bulgular üzerinden belirlenmelidir.", sections: [
    { heading: "Sabit aralık yerine risk temelli plan", body: "Yıllık kontrol birçok işletmenin başlangıç noktası olabilir; ancak bunu her trafo için zorunlu veya yeterli bir teknik kural saymak yanlıştır. Toz, nem, yüksek sıcaklık, ağır yüklenme, sık açma-kapama ve önceki arıza kayıtları kontrol sıklığını artırabilir. Kritik bir tesiste duruşun etkisi de kararın parçasıdır.", bullets: ["Üretici bakım talimatı ve tesis prosedürü", "Yük ve sıcaklık eğilimleri", "Önceki testlerde sapma veya tekrarlayan arıza", "Ortam koşulları ve tesisin kritiklik düzeyi"] },
    { heading: "Bakımın içeriği neden periyodu etkiler?", body: "Gözle muayene, termal tarama, yağ numunesi ve enerjisiz elektriksel test aynı çalışma değildir. Bazıları işletme sırasında izlenebilirken izolasyon ve sargı gibi ölçümler kontrollü kesinti gerektirir. Bu nedenle yıllık saha ziyareti ile her testin yıllık tekrarı aynı anlama gelmez." },
    { heading: "Plan nasıl güncellenir?", body: "Kontrol sonrası bulunan yağ kaçağı, gevşek bağlantı, sıcak nokta veya ölçüm sapması için aksiyon ve tekrar kontrol tarihi kaydedilir. Bir sonraki dönem, yalnızca takvim yılına göre değil bu bulguların eğilimine göre güncellenir. Raporun ekipman etiketi, test koşulu ve ölçüm değerlerini içermesi karşılaştırma açısından önemlidir." },
  ], faq: [{ q: "Her trafoya yılda bir kapsamlı test gerekir mi?", a: "Hayır. Test planı ekipman tipi, üretici talimatı, geçmiş sonuçlar ve işletme riskine göre belirlenir." }, { q: "Bakım planı için hangi bilgi gerekli?", a: "Trafo etiketi, yük profili, ortam koşulları, son bakım ve test raporları başlangıç için önemlidir." }], service: "trafo-bakim-ve-onarimi", equipment: "mt-20k", sources: [sources.maintenance,sources.testing] },
  { id: "ariza-belirtileri", slug: "trafo-arizasi-belirtileri", title: "Trafo arızasının belirtileri nelerdir?", description: "Anormal ses, sıcaklık, yağ kaçağı ve koruma açması gibi işaretler nasıl değerlendirilir? Güvenli ilk adımlar ve teknik teşhis.", intro: "Aşırı ısınma, olağan dışı ses, yağ sızıntısı veya koruma açması erken uyarı olabilir. Fakat tek bir belirti, arızanın yerini veya nedenini kesin olarak göstermez. Önce saha güvenliği sağlanmalı, sonra olay kayıtları ile ölçüm sonuçları birlikte incelenmelidir.", sections: [
    { heading: "Hangi işaretler ciddiye alınmalı?", body: "Normal çalışma sesinden farklı çatırtı veya artan titreşim; yüksek sıcaklık, soğutma yetersizliği, yağ seviyesi düşüşü, duman veya keskin koku gecikmeden değerlendirilmelidir. Röle açması trafonun kendisinden, kablodan, kesiciden veya koruma sisteminden kaynaklanabilir.", bullets: ["Anormal ses, titreşim veya koku", "Yağ kaçağı, seviye ya da sıcaklık değişimi", "Buchholz ve diğer koruma olayları", "Tekrarlayan kesici açması veya gerilim sorunu"] },
    { heading: "Güvenli ilk yaklaşım", body: "Yetkisiz kişiler ekipmandan uzak tutulmalıdır. Enerji kesme, kilitleme ve gerilim yokluğu doğrulaması yalnızca yetkili personelin tesis prosedürüne göre yürütülür. Fotoğraf, olay saati ve röle kayıtları güvenli mesafeden toplanabilir; arıza kaydı silinmemelidir." },
    { heading: "Kök neden nasıl araştırılır?", body: "Saha muayenesi, olay kayıtları, izolasyon direnci, çevirme oranı, sargı direnci ve gerektiğinde yağ testleri farklı olasılıkları daraltır. Ölçümler tek başına hüküm değildir; etiket, geçmiş rapor ve test sıcaklığıyla karşılaştırılır. Onarım sonrası fonksiyon doğrulanmadan yeniden enerjilendirme planlanmaz." },
  ], faq: [{ q: "Koruma rölesi açtıysa trafo kesin arızalı mıdır?", a: "Hayır. Röle olayı, kablo, kesici ve trafo testleriyle birlikte yorumlanmalıdır." }, { q: "Duman veya yanık kokusunda ne yapılmalı?", a: "Alanı güvene alın, yetkisiz yaklaşımı önleyin ve tesisin acil prosedürü ile yetkili teknik ekibe başvurun." }], service: "trafo-ariza-tespiti-ve-giderilmesi", equipment: "mt-ttr3pro", sources: [sources.testing,sources.winding] },
  { id: "yag-analizi", slug: "trafo-yagi-analizi-dga-delinme", title: "Trafo yağı analizi: DGA ve delinme testi", description: "Yağlı trafolarda DGA, nem, asitlik ve dielektrik dayanım testlerinin amacı ve sonuçların birlikte yorumlanması.", intro: "Trafo yağı hem yalıtım hem soğutma işlevi görür. Yağ analizi, ekipmanın iç koşullarına ilişkin veri sağlar; ancak tek bir gaz veya tek bir delinme değeri tek başına kesin arıza kararı değildir.", sections: [
    { heading: "Hangi test hangi soruya yanıt verir?", body: "Dielektrik delinme gerilimi, numunenin elektriksel zorlanmaya dayanımını inceler. Nem ve asitlik ölçümleri yalıtım sisteminin durumuna ilişkin başka veriler sağlar. Çözünmüş gaz analizi (DGA) ise ısıl veya elektriksel olaylarla ilişkili gaz eğilimlerini izlemek için kullanılır.", bullets: ["BDV: yağın dielektrik dayanımı", "Nem ve asitlik: kirlenme ve yaşlanma göstergeleri", "DGA: çözünmüş gazların seviyesi ve değişim hızı", "Numune koşulu ve geçmiş ölçümler: doğru yorumun temeli"] },
    { heading: "Numune neden kritik?", body: "Kirli kap, hava teması, numune alma sıcaklığı ve yanlış etiketleme sonucu bozabilir. Numunenin hangi trafodan, ne zaman ve hangi işletme koşulunda alındığı kayıt altına alınmalıdır. Yağ testinde yöntem ve tekrar sayısı da raporda belirtilir." },
    { heading: "Sonuç nasıl karara dönüşür?", body: "Gaz dağılımı ve artış hızı, yağın geçmiş sonuçları, yük geçmişi, diğer elektriksel testler ve görsel bulgularla birlikte değerlendirilir. Gerektiğinde tekrar numune, filtrasyon, ileri inceleme veya onarım planlanır. Test sıklığı, risk ve üretici önerisine göre belirlenir; her ekipmana sabit altı ay veya bir yıl aralığı dayatılmaz." },
  ], faq: [{ q: "Düşük yağ delinme gerilimi iç arıza demek midir?", a: "Hayır. Numune kalitesi, nem ve kirlenme gibi etkenler de sonucu etkileyebilir; ek verilerle değerlendirilir." }, { q: "DGA her yağ testinin yerine geçer mi?", a: "Hayır. DGA, BDV, nem ve diğer testler farklı soruları yanıtlar." }], service: "trafo-yag-analizi", equipment: "mth-obdv", sources: [sources.oil,sources.bdv] },
  { id: "og-hucre", slug: "og-hucre-bakim-test-rehberi", title: "OG hücre bakımı ve testleri neleri kapsar?", description: "Orta gerilim hücrelerinde kesici, izolasyon, mekanik kilitleme, röle ve fonksiyon testlerinin teknik kapsamı.", intro: "OG hücre, enerjinin güvenli anahtarlanması ve korunmasında kritik bir ekipmandır. Bakım planı yalnızca temizliğe indirgenemez; kesici, bara, kablo başlığı, kilitleme, yardımcı besleme ve koruma birlikte değerlendirilir.", sections: [
    { heading: "Fiziksel ve mekanik kontrol", body: "Ark izi, nem, kirlenme, gevşek bağlantı ve aşınma işaretleri incelenir. Kesici ve ayırıcı mekanizmalarının hareketi, kapı kilitleri ve topraklama ayırıcısı ekipman talimatlarına göre doğrulanır. Sökme ve temas gerektiren işlemler güvenli enerji izolasyonuyla yapılır.", bullets: ["Bara ve kablo sonlandırmaları", "Kesici ve ayırıcı mekanizmaları", "Mekanik kilitleme ve topraklama", "Yardımcı besleme ve kumanda devresi"] },
    { heading: "Elektriksel testler", body: "Hücre ve kesici tipine göre izolasyon direnci, kontak geçiş direnci, açma-kapama zamanlaması ve röle fonksiyonları ölçülebilir. Sekonder enjeksiyon koruma ayar ve açma zincirini sınamak için kullanılır; primer enjeksiyon her sistemde gerekli veya uygun değildir." },
    { heading: "Periyot ve rapor", body: "Üretici talimatı, operasyon sayısı, çevre şiddeti ve önceki bulgular bakım sıklığını etkiler. Anormal işletme veya arıza açması sonrasında plan dışı inceleme gerekebilir. Raporda hücre kimliği, test koşulları, bulgular ve önerilen aksiyon bulunmalıdır." },
  ], faq: [{ q: "OG hücre bakımında enerji kesilir mi?", a: "İç muayene ve temas gerektiren işlemler için güvenli izolasyon ve gerilim yokluğu doğrulaması gerekir." }, { q: "Her hücreye aynı test paketi uygulanır mı?", a: "Hayır. Hücre tipi, kesici yapısı ve koruma düzeni test planını belirler." }], service: "og-hucre-bakim-ve-onarim", sources: [sources.switchgear] },
  { id: "kuru-tip", slug: "kuru-tip-trafo-bakimi", title: "Kuru tip trafo bakımı nasıl planlanır?", description: "Kuru tip trafolarda toz, nem, havalandırma, bağlantı, termal durum ve izolasyon kontrolleri.", intro: "Kuru tip trafoda yağ bulunmaması bakım gereksinimini ortadan kaldırmaz. Toz, nem, havalandırma ve bağlantı sıcaklığı izlenmelidir; yağlı trafoya özgü numune ve DGA testleri ise burada uygulanmaz.", sections: [
    { heading: "Ortam koşulları ve temizlik", body: "Trafo odasındaki hava akışı, filtreler, toz birikimi ve nem kontrol edilir. Temizlik yöntemi ekipmanın üretici talimatına uygun seçilir; uygunsuz basınçlı hava veya solvent yalıtım yüzeylerine zarar verebilir.", bullets: ["Havalandırma kanalları ve fanlar", "Bobin ve izolasyon yüzeyleri", "Toz, nem ve kirlenme", "Sensör ve sıcaklık alarmları"] },
    { heading: "Ölçüm ve termal değerlendirme", body: "Uygun koşullarda bağlantılar, izolasyon direnci ve termal görüntüler incelenir. Daha ileri tanı yöntemleri, ekipmanın yapısı ve belirtiye göre seçilir. Tek bir ölçüm sonucu sıcaklık, test süresi ve geçmiş eğilimden kopuk yorumlanmamalıdır." },
    { heading: "Bakım sonrası kayıt", body: "Tespit edilen kirlenme, gevşeklik, sıcak nokta veya izolasyon şüphesi raporlanır. Düzeltici işlemler ve yeniden ölçüm sonucu aynı ekipman kaydında tutulur. Kontrol aralığı, ortam ve işletme kritikliğine göre güncellenir." },
  ], faq: [{ q: "Kuru tip trafoda yağ analizi yapılır mı?", a: "Hayır. Kuru tip trafoda yağ olmadığı için yağ analizi uygulanmaz." }, { q: "Kuru tip trafo bakım gerektirmez mi?", a: "Hayır. Çevre, soğutma, bağlantı ve yalıtım kontrolleri gerekir." }], service: "kuru-tip-trafo-bakimi", equipment: "mt-20k", sources: [sources.dry,sources.testing] },
  { id: "testler", slug: "trafo-testleri-hangi-testler-yapilir", title: "Trafo testleri: hangi ölçüm neyi gösterir?", description: "TTR, sargı direnci, izolasyon, tanjant delta ve yağ testlerinin amacı ile sonuçların karşılaştırmalı yorumu.", intro: "Trafo testleri, gözle görülemeyen kusurlara ilişkin ölçülebilir veri üretir. Ancak test seçimi arıza belirtisine ve ekipman tipine göre yapılmalıdır; her trafoya her ölçümü otomatik uygulamak doğru değildir.", sections: [
    { heading: "Elektriksel test aileleri", body: "TTR sargılar arasındaki oranı ve kademe davranışını; sargı direnci bağlantı ve temas kusurlarını; izolasyon direnci yalıtımın durumunu inceler. Tanjant delta/kapasitans daha ayrıntılı dielektrik değerlendirmede kullanılır. Yağlı trafoda yağ testleri ayrıca bilgi verir.", bullets: ["TTR: oran ve bağlantı grubu", "Sargı direnci: faz ve kademe karşılaştırması", "İzolasyon direnci: yalıtım eğilimi", "Tanjant delta: dielektrik kayıplar", "Yağ testleri: yağın elektriksel ve kimyasal durumu"] },
    { heading: "Sonuçlar nasıl yorumlanır?", body: "Etiket değerleri, üretici toleransları, sıcaklık, test bağlantısı ve önceki kayıtlar birlikte değerlendirilir. Şüpheli bir değer için önce bağlantı ve yöntem doğrulanır; gerekirse tamamlayıcı test yapılır. Tek bir eşik tüm marka ve modellere uygulanamaz." },
    { heading: "Rapor neden önemlidir?", body: "Ölçüm değeri kadar hangi cihazla, hangi koşulda ve hangi faz/kademe konumunda alındığı da önemlidir. Rapor, ileride yapılacak karşılaştırmaların başlangıç verisini oluşturur ve bakım kararını denetlenebilir kılar." },
  ], faq: [{ q: "TTR testi tek başına yeterli midir?", a: "Hayır. Oran testi belirli kusurları araştırır; diğer testlerle ve ekipman geçmişiyle birlikte değerlendirilir." }, { q: "Bütün testler enerji altında yapılır mı?", a: "Hayır. Birçok elektriksel test güvenli biçimde enerjisiz ekipmanda yapılır." }], service: "trafo-testleri", equipment: "mt-ttr3pro", sources: [sources.ttr,sources.winding,sources.testing] },
  { id: "acil", slug: "acil-trafo-arizasinda-ne-yapilmali", title: "Acil trafo arızasında ne yapılmalı?", description: "Trafo arızasında personel güvenliği, olay bilgileri, profesyonel teşhis ve kontrollü enerjilendirme süreci.", intro: "Ani kesintide amaç ekipmanı mümkün olan en kısa sürede değil, güvenle yeniden işletmeye almaktır. İlk adımlar personel güvenliği, alanın korunması ve yetkili ekibin doğru bilgiyle bilgilendirilmesidir.", sections: [
    { heading: "İlk dakikalarda güvenlik", body: "Duman, yangın, yağ sızıntısı veya ses varsa yetkisiz kişileri uzaklaştırın ve tesisin acil durum prosedürünü uygulayın. Enerji kesme ve müdahale işlemlerini yalnızca yetkili personel yürütmelidir. Ekipmana dokunarak veya yaklaşarak belirti doğrulamaya çalışmayın.", bullets: ["Alanı güvene alın ve erişimi sınırlayın", "Tesis acil durum prosedürünü izleyin", "Olay saatini ve görülen belirtileri kaydedin", "Röle ve kesici kayıtlarını koruyun"] },
    { heading: "Teknik ekibe ne iletilmeli?", body: "Tesis konumu, trafo etiketi, açan koruma elemanı, son bakım tarihi ve varsa önceki test sonuçları ilk değerlendirmeyi hızlandırır. Acil hat, bir telefon iletişim kanalıdır; sahaya varış süresi konum ve ekip uygunluğuna göre görüşme sırasında netleştirilir." },
    { heading: "Güvenli dönüş", body: "Arızanın kaynağı trafo, OG hücre, kablo veya koruma zincirinde olabilir. Görsel inceleme ve uygun ölçümlerin ardından onarım planlanır. Gerekli fonksiyonlar ve güvenlik koşulları doğrulanmadan yeniden enerjilendirme yapılmamalıdır." },
  ], faq: [{ q: "7/24 hat anında saha varışı anlamına gelir mi?", a: "Hayır. Telefon hattı 7/24 açıktır; saha müdahalesi ve varış süresi talep değerlendirmesinde belirlenir." }, { q: "Koruma açmasından sonra hemen tekrar enerji verilir mi?", a: "Neden araştırılmadan ve gerekli kontroller tamamlanmadan tekrar enerjilendirme güvenli değildir." }], service: "acil-mudahale", sources: [sources.testing,sources.switchgear] },
  { id: "ikinci-el", slug: "ikinci-el-trafo-alirken-kontrol-listesi", title: "İkinci el trafo alırken kontrol listesi", description: "İkinci el trafoda etiket, geçmiş, fiziki durum ve temel elektriksel testleri satın alma kararından önce değerlendirin.", intro: "İkinci el trafonun fiyatı kadar geçmişi ve teknik durumu da önemlidir. Eksik kayıt veya test olmadan yapılan alım, montajdan sonra güvenlik ve maliyet riski yaratabilir.", sections: [
    { heading: "Etiket ve kullanım geçmişi", body: "Anma gücü, gerilimler, bağlantı grubu, empedans, üretim yılı ve soğutma türü yeni tesisin ihtiyacıyla uyumlu olmalıdır. Eski bakım, arıza, taşıma ve depolama kayıtları istenir. Etiketi okunmayan ekipman için daha ayrıntılı doğrulama gerekebilir.", bullets: ["Güç, gerilim ve bağlantı grubu", "Fiziki hasar, sızıntı ve korozyon", "Bakım, arıza ve taşıma kayıtları", "Mevcut tesise teknik uygunluk"] },
    { heading: "Test paketi", body: "Yağlı trafoda yağın durumu, kuru tip trafoda yüzey ve havalandırma farklı incelenir. TTR, izolasyon ve sargı direnci gibi testler tip ve koşullara göre seçilir. Sonuçlar etiket ve varsa geçmiş ölçümlerle karşılaştırılmalıdır." },
    { heading: "Satın alma kararı", body: "Sadece geçerli bir test değeri yeterli değildir: garanti koşulları, taşıma, montaj, yedek parça ve devreye alma maliyeti birlikte hesaplanır. Şüpheli bulgular için koşullu kabul, ek test veya vazgeçme kararı teknik rapora dayanmalıdır." },
  ], faq: [{ q: "Test raporu olmadan ikinci el trafo alınır mı?", a: "Alım kararı teknik riski artırır. Ekipmana uygun testler ve geçmiş kayıtlar satın alma öncesi değerlendirilmelidir." }, { q: "Yağlı ve kuru tip için aynı kontrol listesi geçerli mi?", a: "Temel etiket ve elektriksel kontroller ortak olabilir; yağ ve soğutma kontrolleri tipine göre değişir." }], service: "trafo-testleri", equipment: "mt-ttr3pro", sources: [sources.ttr,sources.winding,sources.maintenance] },
];
