export const blogImages: Record<string, { src: string; description: string; source?: string; credit?: string; license?: string }> = {
  "bakim-sikligi": { src: "/images/blog/maintenance-new.jpg", description: "Trafo merkezindeki güç transformatörü", source: "https://commons.wikimedia.org/wiki/File:Power_Transformer_03.jpg", credit: "SoniaBudini · Wikimedia Commons · CC BY-SA 4.0", license: "https://creativecommons.org/licenses/by-sa/4.0/" },
  "ariza-belirtileri": { src: "/images/blog/fault-damage.jpg", description: "Hasar görmüş elektrik transformatörü", source: "https://commons.wikimedia.org/wiki/File:Electrical_transformer_damaged_by_2011_tornado;_Brimfield,_MA.jpg", credit: "Massachusetts Department of Environmental Protection · Wikimedia Commons · CC BY 2.0", license: "https://creativecommons.org/licenses/by/2.0/" },
  "yag-analizi": { src: "/images/blog/oil-test.jpg", description: "Trafo yağının dielektrik delinme testi", source: "https://commons.wikimedia.org/wiki/File:BA75-b2hv-Breakdown-during-transformer-oil-testing.jpg", credit: "HVWeb · Wikimedia Commons · Public domain" },
  "og-hucre": { src: "/images/blog/switchgear.jpg", description: "Orta gerilim şalt ve hücre donanımı", source: "https://commons.wikimedia.org/wiki/File:4.16kV_switchgear.jpg", credit: "Rsparks3 · Wikimedia Commons · CC0" },
  "kuru-tip": { src: "/images/blog/dry-transformer.jpg", description: "Kuru tip transformatör", source: "https://commons.wikimedia.org/wiki/File:Dry_Type_Transformer.jpg", credit: "Tirupatitransformer · Wikimedia Commons · CC BY-SA 4.0", license: "https://creativecommons.org/licenses/by-sa/4.0/" },
  "testler": { src: "/images/blog/transformer-testing.jpg", description: "Saha testinde güç transformatörü", source: "https://commons.wikimedia.org/wiki/File:Substation_transfomer.jpg", credit: "Ptrump16 · Wikimedia Commons · CC BY-SA 4.0", license: "https://creativecommons.org/licenses/by-sa/4.0/" },
  "acil": { src: "/images/blog/emergency.jpg", description: "Elektrik trafo merkezi", source: "https://commons.wikimedia.org/wiki/File:Small_electrical_substation.jpg", credit: "Wikideas1 · Wikimedia Commons · CC0" },
  "ikinci-el": { src: "/images/blog/fault.jpg", description: "Trafo merkezindeki güç transformatörü", source: "https://commons.wikimedia.org/wiki/File:Transformer_at_substation.jpg", credit: "Wikideas1 · Wikimedia Commons · CC0" },
};
