import Image from "next/image";
import Link from "next/link";
import { company, services, references } from "./data";
import { coreServices } from "./core-services";
const nav=[['Hakkımızda','/kurumsal'],['Hizmetler','/hizmetler'],['Faaliyet Alanları','/faaliyet-alanlari'],['Cihaz Parkuru','/cihaz-parkuru'],['Yetkili Servisler','/yetkili-servisler'],['Partnerler','/partnerler'],['Referanslar','/referanslar'],['İletişim','/iletisim']] as const;
export function Header(){return <><div className="topbar"><div className="shell"><span>Ankara merkezli, Türkiye genelinde saha hizmeti</span><span className="languages"><Link href="/en">EN</Link><Link href="/ar">العربية</Link><a href={`mailto:${company.email}`}>{company.email}</a><a href={`mailto:${company.serviceEmail}`}>{company.serviceEmail}</a></span></div></div><header className="site-header"><div className="shell header-inner"><Link href="/" className="brand" aria-label="BES Enerji ana sayfa"><Image src="/images/bes-enerji-logo-concept-v3.png" alt="BES Enerji" width={180} height={75} priority/></Link><nav aria-label="Ana menü">{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}</nav><a className="phone" href={`tel:${company.phone}`}>{company.phoneDisplay}</a><details className="mobile-menu"><summary>Menü</summary><div><Link href="/">Ana Sayfa</Link>{nav.map(([label,href])=><Link href={href} key={href}>{label}</Link>)}<Link href="/kurumsal">Kurumsal</Link><Link href="/cozumler">Çözümler</Link><Link href="/en">English</Link><Link href="/ar">العربية</Link></div></details></div></header></>}
export function ReferenceStrip(){return <section className="reference-strip" aria-labelledby="reference-strip-title"><div className="shell reference-strip-head"><span className="kicker" id="reference-strip-title">Referanslarımız</span><Link href="/referanslar">Tüm referansları inceleyin →</Link></div><div className="reference-marquee"><div className="reference-marquee-track">{[...references,...references].map((item,index)=><div className="reference-logo" key={`${item}-${index}`}><Image src={`/images/${item}`} alt="BES Enerji referans kurumu" width={180} height={90}/></div>)}</div></div></section>}
export function Footer(){return <><ReferenceStrip/><section className="cta-band"><div className="shell cta-band-inner"><div><span className="kicker light">Teknik destek ve keşif</span><h2>Enerji sürekliliğinizi birlikte planlayalım.</h2><p>Trafo ve güç sistemleriniz için teknik ekibimizle görüşün.</p></div><div className="actions"><a className="btn white" href={`tel:${company.phone}`}>Hemen Arayın</a><Link className="btn ghost" href="/iletisim">Teklif İsteyin</Link></div></div></section><footer><div className="shell footer-grid"><div><Image src="/images/bes-enerji-logo-concept-v3.png" alt="BES Enerji" width={180} height={75}/><p>Trafo bakım, test, onarım ve devreye alma hizmetlerinde sahaya özel mühendislik çözümleri.</p></div><div><h3>Hizmetler</h3>{coreServices.slice(0,6).map(s=><Link key={s.slug} href={`/hizmetler/${s.slug}`}>{s.shortTitle}</Link>)}</div><div><h3>Kurumsal</h3><Link href="/kurumsal">Hakkımızda</Link><Link href="/faaliyet-alanlari">Faaliyet Alanları</Link><Link href="/cihaz-parkuru">Cihaz Parkuru</Link><Link href="/yetkili-servisler">Yetkili Servisler</Link><Link href="/partnerler">Partnerler</Link><Link href="/referanslar">Referanslar</Link><Link href="/iletisim">İletişim</Link></div><div><h3>İletişim</h3><a href={`tel:${company.phone}`}>{company.phoneDisplay}</a><a href={`mailto:${company.email}`}>{company.email}</a><a href={`mailto:${company.serviceEmail}`}>{company.serviceEmail}</a><address>{company.address}</address></div></div><div className="shell copyright">© 2026 BES Enerji. Tüm hakları saklıdır.</div></footer><div className="sticky-actions"><a href={`tel:${company.phone}`}>Ara</a><a href="https://wa.me/905532124761" target="_blank" rel="noreferrer">WhatsApp</a></div></>}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumb" aria-label="İçerik yolu"><Link href="/">Ana Sayfa</Link>{items.map((item,index)=><span key={index}>/ {item.href?<Link href={item.href}>{item.label}</Link>:item.label}</span>)}</nav>}
export function ServiceCards(){return <div className="service-grid">{services.map((service,index)=><Link className="service-card" href={`/hizmetler/${service.slug}`} key={service.slug}><span className="number">0{index+1}</span><div className="service-photo"><Image src={service.image} alt={service.title} fill sizes="(max-width: 760px) 100vw, 33vw"/></div><div className="service-body"><h3>{service.title}</h3><p>{service.summary}</p><span className="arrow">Hizmeti inceleyin →</span></div></Link>)}</div>}
