import type { EquipmentSlug } from "./equipment-details";
import type { Locale } from "./localized";

type Detail = { purpose: string; method: string; applications: string[] };
export const localizedEquipment: Record<Exclude<Locale,"tr">, Record<EquipmentSlug, Detail>> = {
  en: {
    "mt-ttr3pro": { purpose: "Compares measured turns ratio with nameplate and tap values; deviations can point to tap-changer, connection or winding issues that need further investigation.", method: "With the transformer isolated and safe, each tap is measured for ratio, phase relationship and deviation. Findings are assessed against the nameplate and previous records.", applications: ["Pre-commissioning ratio verification", "Tap-position comparison", "Post-fault winding and vector-group assessment"] },
    "mt-20k": { purpose: "Helps assess insulation affected by moisture, contamination or ageing. Temperature and previous readings matter more than a single isolated result.", method: "The isolated equipment is tested at an appropriate voltage. Duration and environmental conditions are recorded, and safe discharge is confirmed before disconnecting.", applications: ["Winding-to-earth insulation assessment", "Before-and-after maintenance comparison", "Trend monitoring for MV/HV assets"] },
    "mth-obdv": { purpose: "Measures the dielectric breakdown strength of transformer oil. It does not replace chemical or dissolved-gas analysis when those are needed.", method: "A representative sample is placed in a clean vessel; electrode spacing and rest time follow the selected method. Successive breakdown values are recorded and averaged.", applications: ["Monitoring oil dielectric strength", "Before-and-after oil filtration checks", "Sample assessment to the selected test method"] },
    "mts-twr-40": { purpose: "Differences between phases or tap positions can reveal possible loose connections, contact defects or winding anomalies.", method: "After suitable connections are made, readings are taken once current stabilizes. Each phase and tap is recorded with temperature, and leads remain connected until discharge completes.", applications: ["Phase-to-phase winding comparison", "Tap-changer contact investigation", "Post-repair resistance verification"] },
    "mts-ctd12": { purpose: "Changes in dielectric loss can indicate moisture or insulation ageing; historical readings and test conditions are essential for interpretation.", method: "The connection mode, voltage and frequency are selected for the asset. Tan delta and capacitance are compared with temperature, humidity and earlier reports.", applications: ["Transformer insulation-loss monitoring", "Bushing and HV insulation examination", "Comparison with periodic test history"] },
    "mt-pttr-3b": { purpose: "Verifies ratio and polarity in transformer and CT/PT measurement or protection circuits during commissioning and fault investigation.", method: "Once wiring diagrams and nameplate values are confirmed, ratio and polarity are measured and compared with the design values in the report.", applications: ["CT/PT ratio verification", "Protection-circuit polarity checks", "Commissioning and tap-change testing"] },
  },
  ar: {
    "mt-ttr3pro": { purpose: "تقارن نسبة التحويل المقاسة بقيم اللوحة ووضعيات مغير الجهد؛ وقد يشير الانحراف إلى مشكلة في الوصلات أو الملفات تستلزم فحصاً إضافياً.", method: "بعد عزل المحول وتأمينه، تقاس النسبة وعلاقة الأطوار والانحراف في كل وضعية، ثم تقارن النتائج باللوحة والسجلات السابقة.", applications: ["التحقق من النسبة قبل التشغيل", "مقارنة وضعيات مغير الجهد", "تقييم الملفات ومجموعة التوصيل بعد العطل"] },
    "mt-20k": { purpose: "يساعد في تقييم العزل المتأثر بالرطوبة والتلوث والتقادم. تؤخذ الحرارة والقراءات السابقة في الحسبان بدلاً من الاعتماد على قيمة منفردة.", method: "يُعزل الجهاز ويؤمّن ثم يطبّق جهد الاختبار الملائم، مع تسجيل الزمن والظروف البيئية والتحقق من التفريغ الآمن قبل فصل الوصلات.", applications: ["تقييم عزل الملفات إلى الأرض", "المقارنة قبل الصيانة وبعدها", "متابعة تغير عزل معدات الجهد المتوسط والعالي"] },
    "mth-obdv": { purpose: "يقيس قوة الانهيار العازل لزيت المحول، ولا يحل محل التحليل الكيميائي أو تحليل الغازات الذائبة عند الحاجة إليهما.", method: "توضع عينة ممثلة في وعاء نظيف، وتضبط المسافة بين الأقطاب وفترة الانتظار حسب الطريقة المختارة، ثم تسجل نتائج الانهيار المتتابعة ومتوسطها.", applications: ["مراقبة قوة عزل الزيت", "المقارنة قبل ترشيح الزيت وبعده", "تقييم العينة وفق طريقة الاختبار المختارة"] },
    "mts-twr-40": { purpose: "قد تكشف فروق المقاومة بين الأطوار أو وضعيات المغير عن وصلة مرتخية أو خلل في التلامس أو الملفات.", method: "بعد التوصيل المناسب ينتظر استقرار التيار، وتسجل قيمة كل طور ووضعية مع درجة الحرارة، ولا تفصل الوصلات قبل اكتمال التفريغ.", applications: ["مقارنة مقاومة الملفات بين الأطوار", "فحص تلامسات مغير الجهد", "التحقق من المقاومة بعد الإصلاح"] },
    "mts-ctd12": { purpose: "قد تشير تغيرات فقد العزل إلى الرطوبة أو التقادم، ويجب تفسيرها بالرجوع إلى القراءات السابقة وظروف الاختبار.", method: "يختار نمط التوصيل والجهد والتردد المناسب، وتقارن قيم تان دلتا والسعة مع الحرارة والرطوبة والتقارير السابقة.", applications: ["مراقبة فقد عزل المحول", "فحص البوشنج ومكونات العزل العالي", "مقارنة نتائج الاختبارات الدورية"] },
    "mt-pttr-3b": { purpose: "يتحقق من النسبة والقطبية في دوائر القياس والحماية الخاصة بالمحول ومحولات التيار والجهد أثناء التشغيل الأولي أو بحث الأعطال.", method: "بعد مطابقة مخطط التوصيل وبيانات اللوحة، تقاس النسبة والقطبية وتقارن بقيم التصميم في التقرير.", applications: ["التحقق من نسبة CT/PT", "فحص قطبية دوائر الحماية", "الاختبار عند التشغيل وتغيير المغير"] },
  },
};
