import { translatedServices } from "./localized";

const extra = {
  en: [
    { slug: "transformer-fault-diagnosis-repair", tr: "trafo-ariza-tespiti-ve-giderilmesi", title: "Transformer Fault Diagnosis and Repair", summary: "Systematic diagnosis, root-cause analysis and controlled repair of transformer faults.", intro: "An overheating alarm, oil leak or protection trip can have different causes. We combine event records, physical inspection and suitable electrical tests before selecting a repair.", items: ["Review alarm and protection records", "Inspect oil level, temperature and sealing", "Check bushings and connections", "Perform insulation, ratio and winding tests", "Assess protection and auxiliary systems", "Retest and document the repair"] },
    { slug: "mv-switchgear-maintenance-repair", tr: "og-hucre-bakim-ve-onarim", title: "MV Switchgear Maintenance and Repair", summary: "Planned mechanical, electrical and protection checks for medium-voltage switchgear.", intro: "Switchgear maintenance covers the complete switching and protection chain, from busbars and insulation to breakers, interlocks and control circuits.", items: ["Clean and visually inspect panels", "Check busbar and cable terminations", "Inspect breaker and disconnector mechanisms", "Verify earthing switch and interlocks", "Check relays and auxiliary circuits", "Report findings and corrective work"] },
    { slug: "mv-switchgear-fault-diagnosis", tr: "og-hucre-ariza-tespiti", title: "MV Switchgear Fault Diagnosis and Repair", summary: "Structured diagnosis of switchgear, breaker, relay and control-circuit faults.", intro: "When a panel fails to operate or a breaker trips unexpectedly, we examine the power circuit, control circuit and protection records together.", items: ["Review trip and event records", "Check auxiliary supply and control wiring", "Assess breaker and disconnector mechanisms", "Inspect busbars, cables and insulation", "Verify relay settings and interlocks", "Test functions after corrective work"] },
    { slug: "mv-switchgear-testing", tr: "og-hucre-testleri", title: "MV Switchgear Testing", summary: "Insulation, contact resistance, breaker timing and protection function tests.", intro: "We verify both the physical condition and the switching and protection behavior of MV equipment after maintenance or before commissioning.", items: ["Insulation resistance measurement", "Contact resistance measurement", "Breaker opening and closing time", "Relay secondary injection", "Primary injection when suitable", "Control, earthing and phase checks"] },
    { slug: "engineering-consultancy", tr: "proje-ve-danismanlik", title: "Engineering and Consultancy", summary: "Feasibility, capacity, design and protection advice for substations and MV systems.", intro: "Investment and refurbishment decisions should reflect actual load, equipment capacity and protection requirements. We turn site data into practical engineering scope.", items: ["Review existing installation and single-line diagram", "Analyze load and transformer capacity", "Develop substation and switchgear designs", "Assess short-circuit and protection coordination", "Support relay settings and specifications", "Document expansion and refurbishment options"] },
    { slug: "electrical-contracting", tr: "elektrik-taahhut", title: "Electrical Contracting", summary: "Project-based installation of substations, MV switchgear, cables and electrical infrastructure.", intro: "Installation, testing and commissioning are coordinated against the approved design and the conditions of the operating facility.", items: ["MV installations and substations", "Transformer and switchgear installation", "MV cables and electrical infrastructure", "Busbar and connection work", "Site measurements and tests", "Commissioning and handover documents"] },
    { slug: "emergency-response", tr: "acil-mudahale", title: "Emergency Transformer and MV Response", summary: "Safety-first assessment, fault diagnosis and repair coordination after an outage.", intro: "Personnel safety and secure isolation come first. Response scope and travel time are confirmed after reviewing the incident and team availability.", items: ["Receive incident details and assess immediate risk", "Secure the site and isolate energy", "Inspect transformer, switchgear and protection", "Locate the fault with suitable tests", "Plan repair or component replacement", "Retest before controlled energization"] },
    { slug: "electrical-inspection-compliance", tr: "elektriksel-muayene-test-uygunluk-raporu", title: "Electrical Inspection, Testing and Compliance", summary: "Electrical inspection, measurements, risk findings and technical compliance reports.", intro: "We review installation safety through site inspection and suitable measurements, then prioritize the findings in a technical report.", items: ["Grounding system measurements", "Internal electrical installation checks", "Thermal imaging", "Residual-current and protection checks", "Panels, busbars and connections", "Measurement-based compliance report"] },
  ],
  ar: [
    { slug: "تشخيص-أعطال-المحولات-وإصلاحها", tr: "trafo-ariza-tespiti-ve-giderilmesi", title: "تشخيص أعطال المحولات وإصلاحها", summary: "تشخيص منهجي لأعطال المحولات وتحليل الأسباب الجذرية والإصلاح الآمن.", intro: "قد يكون لارتفاع الحرارة أو تسرب الزيت أو فصل الحماية أسباب مختلفة. نراجع سجل الأحداث والفحص الميداني والاختبارات الكهربائية المناسبة قبل تحديد الإصلاح.", items: ["مراجعة سجلات الإنذار والحماية", "فحص مستوى الزيت والحرارة والتسرب", "فحص العوازل والوصلات", "اختبارات العزل ونسبة التحويل ومقاومة الملفات", "تقييم الحماية والأنظمة المساعدة", "إعادة الاختبار وتوثيق الإصلاح"] },
    { slug: "صيانة-وإصلاح-خلايا-الجهد-المتوسط", tr: "og-hucre-bakim-ve-onarim", title: "صيانة وإصلاح خلايا الجهد المتوسط", summary: "صيانة مخططة وفحوصات ميكانيكية وكهربائية وحماية لخلايا الجهد المتوسط.", intro: "تشمل الصيانة سلسلة الفصل والحماية كاملة، من القضبان والعزل إلى القواطع والتشابكات ودوائر التحكم.", items: ["تنظيف الخلايا وفحصها بصرياً", "فحص القضبان ونهايات الكابلات", "فحص آليات القواطع والفواصل", "التحقق من مفتاح التأريض والتشابكات", "فحص المرحلات والدوائر المساعدة", "تقرير النتائج والإجراءات التصحيحية"] },
    { slug: "تشخيص-أعطال-خلايا-الجهد-المتوسط", tr: "og-hucre-ariza-tespiti", title: "تشخيص وإصلاح أعطال خلايا الجهد المتوسط", summary: "تشخيص أعطال الخلايا والقواطع والمرحلات ودوائر التحكم بطريقة منظمة.", intro: "عند تعطل الخلية أو فصل القاطع بشكل غير متوقع نفحص دائرة القدرة والتحكم وسجلات الحماية معاً.", items: ["مراجعة سجلات الفصل والأحداث", "فحص التغذية المساعدة وأسلاك التحكم", "تقييم آليات القواطع والفواصل", "فحص القضبان والكابلات والعزل", "التحقق من إعدادات المرحلات والتشابكات", "اختبار الوظائف بعد الإصلاح"] },
    { slug: "اختبارات-خلايا-الجهد-المتوسط", tr: "og-hucre-testleri", title: "اختبارات خلايا الجهد المتوسط", summary: "اختبارات العزل ومقاومة الملامسات وتوقيت القاطع ووظائف الحماية.", intro: "نتحقق من الحالة الكهربائية وسلوك الفصل والحماية بعد الصيانة أو قبل التشغيل.", items: ["قياس مقاومة العزل", "قياس مقاومة الملامسات", "قياس زمن فتح وإغلاق القاطع", "اختبار المرحلات بالحقن الثانوي", "الحقن الأولي عند ملاءمة النظام", "فحص التحكم والتأريض وتسلسل الأطوار"] },
    { slug: "الهندسة-والاستشارات", tr: "proje-ve-danismanlik", title: "الهندسة والاستشارات", summary: "دراسات الجدوى والسعة والتصميم والحماية لمحطات التحويل وأنظمة الجهد المتوسط.", intro: "يجب أن تستند قرارات الاستثمار والتجديد إلى الأحمال الفعلية وسعة المعدات ومتطلبات الحماية.", items: ["مراجعة المنشأة والمخطط أحادي الخط", "تحليل الأحمال وسعة المحول", "تصميم المحطة وخلايا الجهد المتوسط", "دراسة القصر وتنسيق الحماية", "دعم إعدادات المرحلات والمواصفات", "توثيق خيارات التوسعة والتجديد"] },
    { slug: "المقاولات-الكهربائية", tr: "elektrik-taahhut", title: "المقاولات الكهربائية", summary: "تركيب محطات التحويل والخلايا والكابلات والبنية الكهربائية وفق المشروع.", intro: "ننسق التركيب والاختبار والتشغيل وفق التصميم المعتمد وظروف المنشأة القائمة.", items: ["منشآت الجهد المتوسط ومحطات التحويل", "تركيب المحولات والخلايا", "كابلات الجهد المتوسط والبنية الكهربائية", "أعمال القضبان والوصلات", "القياسات والاختبارات الميدانية", "وثائق التشغيل والتسليم"] },
    { slug: "الاستجابة-الطارئة", tr: "acil-mudahale", title: "الاستجابة الطارئة للمحولات وخلايا الجهد المتوسط", summary: "تقييم أولي آمن وتشخيص الأعطال وتنسيق الإصلاح بعد انقطاع الطاقة.", intro: "سلامة الأشخاص وعزل الطاقة بأمان هما الأولوية. يُحدد نطاق الاستجابة ووقت الوصول بعد مراجعة الحالة وتوفر الفريق.", items: ["تلقي تفاصيل العطل وتقييم المخاطر", "تأمين الموقع وعزل الطاقة", "فحص المحول والخلية والحماية", "تحديد موضع العطل بالاختبارات المناسبة", "تخطيط الإصلاح أو استبدال القطعة", "إعادة الاختبار قبل التغذية الآمنة"] },
    { slug: "الفحص-الكهربائي-والمطابقة", tr: "elektriksel-muayene-test-uygunluk-raporu", title: "الفحص والاختبار الكهربائي وتقرير المطابقة", summary: "فحص كهربائي وقياسات وتحديد مخاطر وتقارير مطابقة فنية.", intro: "نراجع سلامة المنشأة بالفحص الميداني والقياسات المناسبة ونرتب النتائج حسب الأولوية في تقرير فني.", items: ["قياسات نظام التأريض", "فحص التركيبات الكهربائية الداخلية", "التصوير الحراري", "فحص قواطع التسرب والحماية", "فحص اللوحات والقضبان والوصلات", "تقرير مطابقة مدعوم بالقياسات"] },
  ],
} as const;

export const allLocalizedServices = {
  en: [...translatedServices.en, ...extra.en],
  ar: [...translatedServices.ar, ...extra.ar],
} as const;
