import Image from "next/image";
import Link from "next/link";
import { Header, Footer } from "./components";
import { CoreServiceGrid } from "./core-service-grid";
import { company } from "./data";
import { activityAreas, equipment } from "./seo-data";
import { ActivityIcon } from "./activity-icon";

const quickServices = [
  { icon: "⚡", title: "Arıza tespiti ve onarım", text: "Trafo, OG hücre ve yüksek gerilim arızalarında ölçüme dayalı teşhis ve kontrollü müdahale.", href: "/hizmetler/trafo-ariza-tespiti-ve-giderilmesi" },
  { icon: "↻", title: "Planlı bakım", text: "İşletme sürekliliği için trafo ve hücre ekipmanlarında önleyici bakım.", href: "/hizmetler/trafo-bakim-ve-onarimi" },
  { icon: "✓", title: "Test ve ölçüm", text: "Elektriksel bulgular, teknik değerlendirme ve raporlama ile karar desteği.", href: "/hizmetler/trafo-testleri" },
];

const fieldPhotos = [
  { src: "/images/trafo-bakim-4.webp", title: "Trafo test ve ölçüm", alt: "Trafo yanında ölçüm cihazları" },
  { src: "/images/trafo-bakim-5.webp", title: "Trafo bakım uygulaması", alt: "Trafo üzerinde test ve bakım çalışması" },
  { src: "/images/resim-8.jpeg", title: "OG hücre incelemesi", alt: "OG hücre sisteminde teknik inceleme" },
  { src: "/images/resim-6.jpeg", title: "OG hücre sistemleri", alt: "Orta gerilim hücresi" },
];

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "Electrician", name: "BES Enerji", url: "https://besenerji.net", description: "Trafo ve OG hücre arıza tespiti, bakım, test ve onarım hizmetleri sunan Ankara merkezli mühendislik ekibi.", telephone: company.phone, email: company.email, address: { "@type": "PostalAddress", streetAddress: "29 Ekim Mahallesi 778. Cadde No: 7/5", addressLocality: "Sincan", addressRegion: "Ankara", addressCountry: "TR" }, areaServed: "Türkiye" };
  return <><Header/><main className="bes-home">
    <section className="bes-hero" aria-labelledby="bes-hero-title"><Image src="/images/bes-hero-refined.png" alt="Trafo üzerinde test ve bakım çalışması" fill priority sizes="100vw"/><div className="bes-hero-shade"/><div className="shell bes-hero-content"><span className="bes-eyebrow light">BES ENERJİ · YÜKSEK GERİLİM TEKNİK SERVİS</span><h1 id="bes-hero-title">Trafo ve OG hücre<br/>arıza, bakım ve test<br/>hizmetleri.</h1><div className="bes-hero-rule"/><p>Yüksek gerilim arızalarında doğru teşhis; trafo ve hücre sistemlerinde planlı bakım, güvenli onarım ve elektriksel test çözümleri.</p><div className="bes-hero-actions"><Link className="bes-button bes-button-primary" href="/hizmetler">Hizmetlerimizi inceleyin →</Link><Link className="bes-button bes-button-hero-outline" href="/iletisim">Teknik talep oluşturun</Link></div></div></section>
    <section className="bes-quick-wrap" aria-label="Öne çıkan hizmetler"><div className="shell bes-quick-grid">{quickServices.map(item=><Link className="bes-quick-card" href={item.href} key={item.title}><span className="bes-quick-icon" aria-hidden="true">{item.icon}</span><h2>{item.title}</h2><p>{item.text}</p><span className="bes-arrow">Hizmeti inceleyin →</span></Link>)}</div></section>
    <section className="bes-section bes-about" id="hakkimizda"><div className="shell bes-about-grid"><div className="bes-about-copy"><span className="bes-eyebrow">BES ENERJİ HAKKINDA</span><h2>Enerji altyapınız için güvenilir teknik çözüm ortağı.</h2><p>BES Enerji, deneyimli mühendis ve teknik saha ekibiyle trafo ve orta gerilim hücre sistemlerinde arıza tespiti, bakım, onarım ve test süreçlerine odaklanır. Her tesisin ekipmanını ve işletme koşullarını değerlendirerek uygulanabilir bir saha planı oluşturur.</p><p>Hedefimiz yalnızca arızayı gidermek değil; güvenli çalışmayı sürdürmek, bakım kararlarını ölçümle desteklemek ve sonuçları açık biçimde raporlamaktır.</p><div className="bes-about-points"><span>Ölçüme dayalı teşhis</span><span>Güvenli saha uygulaması</span><span>Trafo ve hücre odağı</span><span>Teknik raporlama</span></div><Link className="bes-button bes-button-primary" href="/kurumsal">BES Enerji’yi tanıyın →</Link></div><div className="bes-about-media"><Image src="/images/trafo-bakim-4.webp" alt="Trafo ve test cihazlarıyla teknik saha çalışması" fill sizes="(max-width: 780px) 100vw, 48vw"/><div>Ölçümden teknik karara<br/>izlenebilir saha süreci</div></div></div></section>
    <section className="bes-section bes-services" id="hizmetlerimiz"><div className="shell"><div className="bes-section-heading"><span className="bes-eyebrow">HİZMETLERİMİZ</span><h2>Trafo ve OG hücre için uçtan uca teknik servis.</h2><p>Bakım, arıza ve test başlıklarını ekipman türüne göre ayırdık. Her hizmetin kapsamını ve uygulama adımlarını ayrı sayfada inceleyebilirsiniz.</p></div><CoreServiceGrid compact/><div className="bes-section-link"><Link href="/hizmetler">Tüm hizmetleri ve teknik kapsamları inceleyin →</Link></div></div></section>
    <section className="bes-section bes-feature"><div className="shell bes-feature-grid"><div><span className="bes-eyebrow">ÖNE ÇIKAN HİZMET</span><h2>Trafo bakım ve onarımında ölçüme dayalı yaklaşım.</h2><p>Trafo bakımı yalnızca periyodik bir kontrol değil; enerji sürekliliğini etkileyen risklerin erken görülmesi için planlanan teknik bir süreçtir. Ekipman durumunu yerinde inceler, test sonuçlarını ve bakım bulgularını birlikte değerlendiririz.</p><ul><li>Genel fiziksel ve mekanik kontrol</li><li>Bağlantı ve izolasyon değerlendirmesi</li><li>Uygun elektriksel test ve ölçümler</li><li>Bulguların teknik raporlanması</li></ul><Link className="bes-button bes-button-primary" href="/hizmetler/trafo-bakim-ve-onarimi">Trafo bakımını inceleyin →</Link></div><div className="bes-feature-media"><Image src="/images/bes-hero-refined.png" alt="Trafo bakımında çalışan teknik ekip" fill sizes="(max-width: 780px) 100vw, 43vw"/></div></div></section>
    <section className="bes-section bes-activities" id="faaliyet-alanlari"><div className="shell"><div className="bes-section-heading"><span className="bes-eyebrow">FAALİYET ALANLARI</span><h2>İşletmeden acil müdahaleye teknik kapsam.</h2><p>Saha hizmetini tek işlem olarak değil, tesisin yaşam döngüsü boyunca süren bir teknik sorumluluk olarak ele alıyoruz.</p></div><div className="bes-activities-grid">{activityAreas.map((item,index)=><Link href="/faaliyet-alanlari" key={item.title}><ActivityIcon index={index}/><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></Link>)}</div></div></section>
    <section className="bes-section bes-equipment" id="cihaz-parkuru"><div className="shell"><div className="bes-equipment-head"><div><span className="bes-eyebrow">CİHAZ PARKURU</span><h2>Doğru teşhis için doğru ölçüm cihazı.</h2><p>BES Enerji envanterindeki test cihazlarıyla trafo ve OG ekipmanlarının durumunu ölçüme dayalı değerlendiriyoruz. Modellerin teknik özelliklerini inceleyin.</p></div><Link className="bes-button bes-button-secondary" href="/cihaz-parkuru">Tüm cihazları görün →</Link></div><div className="bes-equipment-grid">{equipment.map(item=><article key={item.code}><div className="bes-equipment-image"><Image src={item.image} alt={`${item.code} ${item.name}`} fill sizes="(max-width: 700px) 100vw, (max-width: 1080px) 50vw, 33vw"/></div><div className="bes-equipment-body"><small>{item.code}</small><h3>{item.name}</h3><p>{item.specs[0]}. {item.specs[1]}.</p><Link href={`/cihaz-parkuru/${item.code.toLowerCase()}`}>Cihaz detayları →</Link></div></article>)}</div></div></section>
    <section className="bes-section bes-field"><div className="shell"><div className="bes-section-heading"><span className="bes-eyebrow">SAHADAN GÖRÜNTÜLER</span><h2>Teknik işin merkezinde saha var.</h2><p>Trafo bakım ve test çalışmalarından, OG hücre incelemelerinden saha görüntüleri.</p></div><div className="bes-field-grid">{fieldPhotos.map(photo=><figure key={photo.src}><div><Image src={photo.src} alt={photo.alt} fill sizes="(max-width: 700px) 50vw, 25vw"/></div><figcaption>{photo.title}</figcaption></figure>)}</div></div></section>
    <section className="bes-section bes-faq"><div className="shell bes-faq-grid"><div><span className="bes-eyebrow">TEKNİK BİLGİ</span><h2>Trafo bakımı neden önemlidir?</h2><p>Planlı bakım; bağlantı gevşemesi, izolasyon zayıflaması, soğutma ve yağ sorunları gibi riskleri arızaya dönüşmeden değerlendirmeye yardımcı olur. Testler bakım kararlarının gözleme değil ölçüme dayanmasını sağlar.</p><Link className="bes-button bes-button-primary" href="/hizmetler/trafo-bakim-ve-onarimi">Bakım hizmetini inceleyin →</Link></div><div className="bes-faq-list"><details open><summary>Trafo bakımı ne zaman planlanmalı?</summary><p>Aralık, ekipman tipi, üretici tavsiyesi, yük ve ortam koşullarına göre belirlenir. İlk adım ekipman geçmişinin ve işletme şartlarının incelenmesidir.</p></details><details><summary>Trafo testleri hangi kararları destekler?</summary><p>İzolasyon, oran, sargı direnci ve yağ testleri ekipman durumunu anlamaya ve müdahale kapsamını belirlemeye yardımcı olur.</p></details><details><summary>İkinci el trafo kullanılmadan önce ne kontrol edilmeli?</summary><p>Görsel durum, etiket bilgileri ve ekipmana uygun elektriksel test sonuçları birlikte değerlendirilmelidir.</p></details></div></div></section>
    <section className="dark-section"><div className="shell value-grid"><article><h2>10 yıllık saha tecrübesi</h2><p>Trafo ve OG hücre sistemlerinde arıza, bakım ve test birikimi.</p></article><article><h2>100’ü aşkın başarılı çalışma</h2><p>Farklı tesis koşullarında tamamlanan teknik saha uygulamaları.</p></article><article><h2>7/24 acil arıza hattı</h2><p>Haftada 6 gün hizmet; acil arızalar için kesintisiz telefon bağlantısı.</p></article></div></section>
  </main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema).replace(/</g,"\\u003c")}}/></>;
}
