import Image from "next/image";import Link from "next/link";import {Header,Footer} from "./components";import {CoreServiceGrid} from "./core-service-grid";import {company} from "./data";import{activityAreas}from"./seo-data";import{ActivityIcon}from"./activity-icon";
export default function Home(){const schema={"@context":"https://schema.org","@type":"Electrician",name:"BES Enerji",telephone:company.phone,email:company.email,address:{"@type":"PostalAddress",streetAddress:"29 Ekim Mahallesi 778. Cadde No: 7/5",addressLocality:"Sincan",addressRegion:"Ankara",addressCountry:"TR"},areaServed:"Türkiye"};return <><Header/><main>
<section className="home-hero"><Image src="/images/bes-hero-concept.png" alt="Trafo ve yüksek gerilim tesisi görseli" fill priority sizes="100vw"/><div className="hero-shade"/><div className="shell hero-copy"><span className="kicker light">Trafo servis ve mühendislik hizmetleri</span><h1>Trafo ve OG hücre sistemlerinde profesyonel bakım, test ve teknik servis.</h1><p>Bakım, arıza teşhisi, onarım ve devreye alma çalışmalarını sahaya özel planlıyor; ölçülebilir sonuçlarla raporluyoruz.</p><div className="actions"><Link className="btn primary" href="/hizmetler">Hizmetleri inceleyin</Link><Link className="btn ghost" href="/iletisim">Teknik talep oluşturun</Link></div></div></section>
<section className="trust-strip"><div className="shell"><span>Planlı bakım</span><span>Kalibre ölçüm cihazları</span><span>Teknik raporlama</span><span>İş güvenliği odağı</span></div></section>
<section className="section home-about"><div className="shell about-layout"><div className="about-image"><Image src="/images/resim-4.jpeg" alt="BES Enerji mühendislik ve saha ekibi" fill sizes="(max-width:760px) 100vw, 48vw"/></div><div><span className="kicker">BES Enerji hakkında</span><h2>Enerji tesislerinde güvenilir ve ölçülebilir mühendislik.</h2><p className="lead">BES Enerji, enerji altyapılarının güvenli ve kesintisiz çalışması için bakım, test, onarım, devreye alma ve işletme sorumluluğu hizmetleri sunar.</p><p>Her tesisi kendi yük profili, ekipman geçmişi ve çalışma koşullarıyla değerlendirir; saha uygulamalarını ölçüm sonuçlarıyla doğrular, karar verilebilir teknik raporlara dönüştürürüz.</p><Link className="text-link" href="/kurumsal">Hakkımızda daha fazlası →</Link></div></div></section>
<section className="soft-section home-activities"><div className="shell"><div className="section-head"><div><span className="kicker">Faaliyet alanlarımız</span><h2>Planlamadan acil müdahaleye tek teknik ekip.</h2></div><Link className="text-link" href="/faaliyet-alanlari">Tüm faaliyet alanları →</Link></div><div className="activity-grid compact">{activityAreas.map((item,index)=><article key={item.title}><ActivityIcon index={index}/><div><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></div></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div><span className="kicker">Dokuz ana hizmetimiz</span><h2>Trafo, OG hücre ve mühendislik hizmetleri.</h2></div><p>Bakım öncesinden arıza müdahalesine kadar hizmetlerimizi açık kategorilerde inceleyin.</p></div><CoreServiceGrid compact/></div></section>
<section className="home-seo"><div className="shell home-seo-grid"><article><span className="kicker">Trafo bakımı</span><h2>Trafo bakımı nedir, neden önemlidir?</h2><p>Planlı bakım; izolasyon, bağlantılar, yağ ve soğutma sistemleri gibi kritik noktaların düzenli değerlendirilmesini sağlar. Amaç, arıza belirtilerini erken görmek ve işletme kararlarını ölçüme dayandırmaktır.</p><Link className="text-link" href="/hizmetler/trafo-bakim-ve-onarimi">Trafo bakımını inceleyin →</Link></article><article><span className="kicker">OG hücre bakımı</span><h2>OG hücre bakım ve testlerinde teknik yaklaşım</h2><p>Kesici, ayırıcı, bara, kilitleme ve koruma devreleri birlikte incelenir. Kontak, izolasyon ve fonksiyon testleri, hücrenin güvenli anahtarlama görevini doğrulamaya yardımcı olur.</p><Link className="text-link" href="/hizmetler/og-hucre-bakim-ve-onarim">OG hücre hizmetini inceleyin →</Link></article></div></section>
<section className="dark-section"><div className="shell split"><div><span className="kicker light">Neden BES Enerji?</span><h2>Sahada doğru teşhis, masada net rapor.</h2><p>Her tesisi kendi çalışma koşullarıyla değerlendirir, yalnızca gerekli işlemleri öneririz. Güvenlikten ödün vermeden planlı, şeffaf ve takip edilebilir hizmet sunarız.</p><Link className="text-link light" href="/kurumsal">Bizi daha yakından tanıyın →</Link></div><div className="metric-grid">{["Keşif ve risk değerlendirmesi","Bakım ve test planı","Saha uygulaması","Rapor ve öneriler"].map((item,index)=><div key={item}><strong>0{index+1}</strong><span>{item}</span></div>)}</div></div></section>
<section className="section solutions-preview"><div className="shell"><div className="section-head"><div><span className="kicker">Sahada sunduğumuz çözümler</span><h2>Gerçek ekipman, sahaya özel teknik yaklaşım.</h2></div><Link className="text-link" href="/cozumler">Tüm çözümleri inceleyin →</Link></div><div className="photo-grid">{[2,6,9].map((number,index)=><div className={`photo p${index+1}`} key={number}><Image src={`/images/resim-${number}.jpeg`} alt={`BES Enerji saha çözümü ${index+1}`} fill sizes="(max-width:760px) 100vw, 50vw"/></div>)}</div></div></section>
</main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></>}
