export const cityPages=[
{slug:"ankara",name:"Ankara",context:"organize sanayi bölgeleri, üretim tesisleri, kamu yapıları ve ticari işletmeler",focus:"Kamu ve üretim tesislerinde planlı kesinti penceresine uygun trafo ve OG hücre kontrolü, koruma sistemlerinin doğrulanması ve bakım kayıtlarının düzenli tutulması öne çıkar."},
{slug:"istanbul",name:"İstanbul",context:"sanayi tesisleri, lojistik merkezleri, hastaneler, oteller ve yüksek katlı ticari yapılar",focus:"Kesintiye hassas işletmelerde bakımın yük aktarımı ve işletme programıyla birlikte planlanması; arıza sonrası testlerin yeniden enerjilendirme kararına temel oluşturması önemlidir."},
{slug:"izmir",name:"İzmir",context:"Aliağa ve çevresindeki sanayi tesisleri, liman işletmeleri, üretim merkezleri ve ticari yapılar",focus:"Liman ve ağır sanayi uygulamalarında trafo soğutması, bağlantı noktaları, yağ durumu ve OG hücre ekipmanları birlikte değerlendirilerek duruş riski azaltılabilir."},
{slug:"adana",name:"Adana",context:"organize sanayi bölgesi, tarıma dayalı üretim tesisleri, soğuk hava depoları ve ticari işletmeler",focus:"Yüksek ortam sıcaklığı ve mevsimsel yük değişimleri bulunan tesislerde sıcaklık izleme, bağlantı kontrolü ve yük altında çalışma geçmişi bakım planına dahil edilmelidir."},
{slug:"bursa",name:"Bursa",context:"otomotiv, tekstil ve makine sanayisi tesisleri ile organize sanayi bölgeleri",focus:"Üretim hattının sürekliliği için duruş zamanı önceden belirlenir; trafo testleri ile kesici ve hücre kontrolleri aynı saha programında koordine edilir."},
{slug:"kocaeli",name:"Kocaeli",context:"ağır sanayi, kimya, otomotiv, liman ve lojistik tesisleri",focus:"Yoğun endüstriyel yükler ve kritik prosesler için bakım öncesi risk değerlendirmesi, yağ ve izolasyon ölçümleri ile koruma düzeninin doğrulanması önceliklidir."},
{slug:"konya",name:"Konya",context:"makine, döküm, gıda ve tarımsal üretim tesisleri ile organize sanayi bölgeleri",focus:"Döküm ve makine tesislerindeki değişken yük koşulları dikkate alınarak trafo bağlantıları, sargı ölçümleri ve koruma ekipmanları birlikte incelenir."},
{slug:"gaziantep",name:"Gaziantep",context:"tekstil, gıda, plastik ve ihracat odaklı üretim tesisleri",focus:"Vardiyalı çalışan üretim tesislerinde planlı kesinti süresi sınırlı olabilir; test sırası ve raporlama önceden netleştirilerek enerji sürekliliği gözetilir."},
{slug:"antalya",name:"Antalya",context:"turizm tesisleri, oteller, hastaneler, alışveriş merkezleri ve tarımsal işletmeler",focus:"Sezonluk yüksek yükler ve iklim koşulları için bakım takvimi yoğun dönem öncesine alınabilir; soğutma, bağlantı ve izolasyon bulguları karşılaştırılır."},
{slug:"mersin",name:"Mersin",context:"liman, lojistik, gıda, depolama ve endüstriyel üretim tesisleri",focus:"Liman ve depolama tesislerinde enerji kesintisinin operasyon etkisi ile kıyı ortamının ekipman üzerindeki koşulları birlikte dikkate alınarak saha planı yapılır."},
{slug:"kayseri",name:"Kayseri",context:"mobilya, metal, tekstil ve makine üretim tesisleri",focus:"Üretim vardiyalarına uygun bakım penceresi belirlenir; trafo sargı ve izolasyon testleri önceki raporlarla karşılaştırılarak önleyici aksiyon planı oluşturulur."},
{slug:"manisa",name:"Manisa",context:"elektronik, beyaz eşya, gıda ve organize sanayi tesisleri",focus:"Otomasyon yoğun tesislerde trafo ve OG dağıtım ekipmanlarının test sonuçları birlikte değerlendirilerek beklenmedik duruş nedenleri araştırılır."},
{slug:"tekirdag",name:"Tekirdağ",context:"Çorlu ve Çerkezköy çevresindeki tekstil, kimya ve üretim tesisleri",focus:"Organize sanayi tesislerinde bağlantı ısınması, yağ durumu ve koruma cihazı kontrolleri bakım programının temel başlıkları arasında ele alınır."},
{slug:"samsun",name:"Samsun",context:"liman, lojistik, sağlık ve Karadeniz bölgesi üretim tesisleri",focus:"Kıyı koşulları ve kritik yüklerin bulunduğu yapılarda hücre temizliği, izolasyon kontrolleri ve arıza sonrası yeniden devreye alma testleri önem kazanır."},
{slug:"eskisehir",name:"Eskişehir",context:"havacılık, seramik, makine ve organize sanayi tesisleri",focus:"Süreç kalitesinin önemli olduğu üretim alanlarında bakım bulguları ölçüm verileriyle kaydedilir ve planlı duruşlara göre test takvimi oluşturulur."},
{slug:"sanliurfa",name:"Şanlıurfa",context:"tarımsal sulama, gıda işleme, soğuk depolama ve organize sanayi tesisleri",focus:"Sulama ve soğutma yüklerinin dönemsel artışı dikkate alınarak trafo yüklenmesi, soğutma ve bağlantı kontrolleri sezon öncesinde planlanabilir."},
{slug:"hatay",name:"Hatay",context:"sanayi, lojistik, liman bağlantılı işletmeler ve yeniden kurulan ticari tesisler",focus:"Tesisin mevcut proje ve ekipman geçmişi doğrulanarak trafo ve hücrelerin durumu değerlendirilir; bakım veya yeniden devreye alma kapsamı sahadaki bulgulara göre netleştirilir."},
{slug:"diyarbakir",name:"Diyarbakır",context:"organize sanayi, sağlık, tarıma dayalı üretim ve ticari tesisler",focus:"Sıcak mevsimlerde artan yük ve tesisin çalışma düzeni dikkate alınarak soğutma, izolasyon ve koruma sistemlerinin test sırası planlanır."},
{slug:"balikesir",name:"Balıkesir",context:"gıda, tarım, sanayi ve turizm tesisleri",focus:"Dağınık yerleşimli üretim ve turizm tesislerinde bakım kapsamı, kesinti planı ve ekipman kayıtları önceden alınarak saha çalışması verimli şekilde düzenlenir."},
{slug:"denizli",name:"Denizli",context:"tekstil, mermer, makine ve organize sanayi tesisleri",focus:"Sürekli veya vardiyalı çalışan hatlarda trafo testleri ile OG hücre kontrolleri koordineli yürütülür; ölçüm eğilimleri sonraki bakım kararına temel oluşturur."},
] as const;

export const activityAreas=[
{title:"YG İşletme Sorumluluğu",text:"Yüksek gerilim tesislerinin mevzuata uygun, güvenli ve kayıtlı biçimde işletilmesi için periyodik kontrol, koordinasyon ve teknik sorumluluk desteği."},
{title:"Planlı Bakım ve Ölçüm",text:"Trafo, hücre, kesici, bara ve koruma sistemleri için duruş planına uyumlu bakım, test ve ölçüm programları."},
{title:"Kurulum ve Devreye Alma",text:"Yeni veya yenilenen enerji tesislerinde montaj kontrolü, fonksiyon testleri, enerjilendirme ve teslim raporlaması."},
{title:"Elektriksel Muayene ve Uygunluk",text:"Topraklama, termal ölçüm, iç tesisat ve ekipman kontrollerinin bulgularla birlikte teknik rapora dönüştürülmesi."},
{title:"Arıza, Onarım ve Acil Müdahale",text:"Trafo ve güç sistemlerinde arıza analizi, güvenli müdahale, onarım koordinasyonu ve yeniden devreye alma desteği."},
{title:"Mühendislik ve Danışmanlık",text:"Fizibilite, kapasite değerlendirmesi, koruma yaklaşımı, bakım stratejisi ve teknik şartname desteği."},
] as const;

export const equipment=[
{name:"Trafo Çevirme Oranı Test Cihazı",code:"MT-TTR3PRO",image:"/images/equipment/mt-ttr3pro.webp",source:"https://testcihazlari.com.tr/trafo-cevirme-orani-test-cihazi-ttr/",specs:["Üç fazlı TTR ölçümü","Bağlantı grubu ve polarite kontrolü","Saha raporlamasına uygun kayıt"]},
{name:"İzolasyon Direnci Test Cihazı",code:"MT-20K",image:"/images/equipment/mt-20k.webp",source:"https://testcihazlari.com.tr/transformator-izolasyon-direnci-test-cihazi/",specs:["20 kV izolasyon direnci ölçümü","Polarizasyon indeksi değerlendirmesi","Bakım öncesi ve sonrası karşılaştırma"]},
{name:"Trafo Yağı Delinme Test Cihazı",code:"MTH-OBDV",image:"/images/equipment/mth-obdv.webp",source:"https://testcihazlari.com.tr/tasinabilir-trafo-yagi-delinme-test-cihazi/",specs:["80/100 kV dielektrik dayanım testi","Kontrollü test dizisi","Yağ bakım kararına teknik veri"]},
{name:"Sargı Direnci Ölçüm Cihazı",code:"MTS-TWR-40",image:"/images/equipment/mts-twr-40.webp",source:"https://testcihazlari.com.tr/trafo-sargi-direnci-olcer-40-amper/",specs:["40 A DC sargı direnci ölçümü","Kademe ve temas kusuru analizi","Düşük direnç hassas ölçümü"]},
{name:"Tanjant Delta Test Cihazı",code:"MTS-CTD12",image:"/images/equipment/mts-ctd12.webp",source:"https://testcihazlari.com.tr/tanjant-delta-test-cihazi-mts-ctd12/",specs:["İzolasyon kayıp faktörü analizi","Kapasitans ölçümü","Saha tipi kompakt test sistemi"]},
{name:"CT/PT Çevirme Oranı Test Cihazı",code:"MT-PTTR-3B",image:"/images/equipment/mt-pttr-3b.webp",source:"https://testcihazlari.com.tr/trafo-cevirme-orani-test-cihazi-ct-pt/",specs:["Akım ve gerilim trafosu oran testi","Polarite ve uyartım değerlendirmesi","Taşınabilir saha uygulaması"]},
] as const;
